from typing import Protocol


class RouterAPI(Protocol):
    def get_wan_proto(self) -> str | None: ...

    def make_pppoe_reconnection(self) -> bool: ...

    def dhcp_renew(self) -> bool: ...

    def get_connected_devices(self) -> list: ...
